version: 2

updates:
  - package-ecosystem: npm
    directory: /angular
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /angular/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /astro
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /astro-starlight
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /astro-starlight/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /astro-tailwind
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /astro-tailwind/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /astro/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /bun/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /cloudflare-worker
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /cloudflare-worker/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /create-t3-app
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /create-t3-app/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /deno-fresh/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /deno/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /docker/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /docusaurus
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /docusaurus/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /gatsby
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /gatsby/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /go/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /nextjs
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /nextjs-app-router
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /nextjs-app-router/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /nextjs/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /node
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /node-http-server
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /node-http-server/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /node/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /nodebox-starter
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /nuxt
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /python-flask-server
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /python-flask-server/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /python/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /qwik-vite
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /qwik-vite/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /react-native-expo
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /react-native-expo/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /react-vite-ts
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /react-vite-ts/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /remix
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /remix/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: cargo
    directory: /rust-poem-server
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /rust-poem-server/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: cargo
    directory: /rust-serde
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /rust-serde/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /rust/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /solid-vite
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /sveltekit
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /sveltekit/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /vite-ts
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /vite-ts/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /vue-vite
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /vue-vite/.codesandbox
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
