version: 2
updates:
  - package-ecosystem: npm
    directory: /angular
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /angular/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /astro
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /astro-starlight
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /astro-starlight/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /astro-tailwind
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /astro-tailwind/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /astro/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /bun/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /cloudflare-worker
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /cloudflare-worker/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /create-t3-app
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /create-t3-app/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /deno-fresh/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /deno/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /docker/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /docusaurus
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /docusaurus/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: mix
    directory: /elixir
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /elixir/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /gatsby
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /gatsby/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /go/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /nextjs
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /nextjs-app-router
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /nextjs-app-router/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /nextjs/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /node
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /node-http-server
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /node-http-server/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /node/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /nodebox-starter
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /nodebox-starter/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /nuxt
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /nuxt/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /python-flask-server
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /python-flask-server/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /python/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /qwik-vite
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /qwik-vite/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /react-native-expo
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /react-native-expo/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /react-vite-ts
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /react-vite-ts/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /remix
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /remix/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: cargo
    directory: /rust-poem-server
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /rust-poem-server/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: cargo
    directory: /rust-serde
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /rust-serde/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /rust/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /solid-vite
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /solid-vite/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /sveltekit
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /sveltekit/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /vite-ts
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /vite-ts/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /vue-vite
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: docker
    directory: /vue-vite/.devcontainer
    schedule:
      interval: daily
    groups:
      deps:
        patterns:
          - '*'
