# CodeSandbox supports debian & ubuntu based images
# This universal image contains almost all languages and tools
FROM ghcr.io/codesandbox/devcontainers/universal:latest

# Example: install htop by default
# RUN apt update -y && apt install -y htop

# The project will be mounted in /workspace by default

# Every new shell will open inside the built container

# On top of this build, we install `zsh`, `git` and `docker` as additional
# Docker layers.
