name: Generate Files

on:
  push:
    paths-ignore:
      - 'templates.json'
      - 'README.md'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR head
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }} # GH PAT for codesandbot

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
      
    - name: Run Deno Script
      run: deno run --allow-read --allow-write --allow-net .scripts/generate-files.ts

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.3
      with:
        message: 'Update files with new template info'
